version: 0.2

phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws --version
      - $(aws ecr get-login --region eu-east-1 --no-include-email)
  build:
    commands:
      - echo Build started on `date`
      - echo Building the Docker image...          
      - docker build -t DotNetCore:latest .
      - docker tag DotNetCore:latest 231573846347.dkr.ecr.us-east-1.amazonaws.com/myecr:latest
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker images...
      - docker push 231573846347.dkr.ecr.us-east-1.amazonaws.com/myecr:latest
      - echo Writing image definitions file...
artifacts:
    files: imagedefinitions.json
